name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # change if needed

      - name: Copy SSH key and set permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}    # optional; set to 22 if used
          script: |
            set -e
            cd /var/www/YOUR_REPO_NAME || exit 1
            git fetch --all
            git reset --hard origin/main
            # Backend
            cd backend || exit 1
            npm install --production
            pm2 restart backend || pm2 start server.js --name backend
            # Frontend
            cd ../frontend || exit 1
            npm ci
            npm run build
            # move build to webroot (if using /var/www/site)
            # cp -r dist/* /var/www/site/
            sudo systemctl reload nginx || sudo systemctl restart nginx
